name:                parsec101
version:             0.1.0.0
github:              "rafaelbreno/parsec101"
license:             BSD3
author:              "Rafael Breno"
maintainer:          "example@example.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rafaelbreno/parsec101#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  parsec101-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parsec101

tests:
  parsec101-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parsec101
